Cancel upload if file is not exists
GooBox/goobox-sync-storj pull request #123
Opened 2018-05-11 08:33 UTC by jasonwee

This is for issue #63 and with this change, when user delete the file during uploading, if the file is not exists, upload will get cancel. In the mentioned issues, there are basically three points:
* If a user deletes a file while its being uploaded, cancel the upload.
* If its renamed when uploading, cancel the upload
* if a user moves the file while uploading, cancel the upload. Then upload it again once the user is done with the task..
Tested these scenarios work on my linux platform, although the reported issue is with windows or mac. On the file is open during user delete/rename on the file, also cannot reproduce in linux platform. Can anymore test this branch on windows/mac?

2018-05-13 19:19 UTC, kaloyan-raev requested changes
I think you got it right. I have just a few style comments.

2018-05-13 19:19 UTC, kaloyan-raev commented on src/main/java/io/goobox/sync/storj/UploadFileTask.java
> +                    if (!file.exists()) {
You can use `Files.exists(path)` directly.

2018-05-13 19:19 UTC, kaloyan-raev commented on src/main/java/io/goobox/sync/storj/UploadFileTask.java
> +    private Long uploadPointer;
`uploadState` or just `state` would be a better name.

2018-05-13 19:19 UTC, kaloyan-raev commented on src/main/java/io/goobox/sync/storj/UploadFileTask.java
> +    private Long uploadPointer;
Also no need to be `Long` object. Could be just the `long` primitive type.

2018-05-13 19:19 UTC, kaloyan-raev commented on src/main/java/io/goobox/sync/storj/UploadFileTask.java
> +    public boolean cancelUpload(Long id) {
I don't see the benefit of this new public method. You could just have the code inline above in `onProgress()`.

2018-05-13 19:19 UTC, kaloyan-raev commented on src/main/java/io/goobox/sync/storj/UploadFileTask.java
> +                        logger.debug("file is not exists (rename, delete or moved), cancelling upload");
You log one `debug` and one `info` message for the same thing. Better have only one info message saying something like:
File {} does not exist anymore (renamed, deleted or moved). Canceling upload."

2018-05-18 07:03 UTC, jasonwee commented on src/main/java/io/goobox/sync/storj/UploadFileTask.java
> +    public boolean cancelUpload(Long id) {
I have made necessary changes except retain `cancelUpload` because variable `uploadState` is not visible in the method `onProgress`

2018-05-18 08:56 UTC, kaloyan-raev commented on src/main/java/io/goobox/sync/storj/UploadFileTask.java
> +    public boolean cancelUpload(Long id) {
I don't understand what you mean. You actually pass `uploadState` as parameter to `cancelUpload()` from `onProgress()`: https://github.com/GooBox/goobox-sync-storj/pull/123/files#diff-9be6731b6a200e181a4b60383c0d5b8fR76

2018-05-18 09:17 UTC, kaloyan-raev approved these changes
Perfect, thanks!

2018-05-18 09:18 UTC, merged